
on: [push]
#on:
#  release:
#    types: [published]

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    name: Build Dockerfile and push to Dockerhub
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Timbermill Server
        run: mvn -B package -DskipTests --file timbermill-java/pom.xml
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ozafar2021
          password: CleanComicChampion6
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./timbermill-java/timbermill-server/
          push: true
          tags: ozafar2021/test:latest
#          tags: salesforce/timbermill-open-source:latest

